###############################################################
#  Generated by:      Cadence Innovus 21.13-s100_1
#  OS:                Linux x86_64(Host ID el103-08.ece.usu.edu)
#  Generated on:      Thu Nov 30 01:21:47 2023
#  Design:            core
#  Command:           saveFPlan ../../scripts/innovus/core.fp
###############################################################

Version: 8

Head Box: 0.0000 0.0000 380.8000 373.5200
IO Box: 0.0000 0.0000 380.8000 373.5200
Core Box: 20.1600 20.1600 360.6400 353.3600
UseStdUtil: false

######################################################
#  DesignRoutingHalo: <space> <bottomLayerName> <topLayerName>
######################################################

######################################################
#  Core Rows Parameters:                             #
######################################################
Row Spacing = 0.000000
Row SpacingType = 2
Row Flip = 2
Core Row Site: core_2800 

##############################################################################
#  DefRow: <name> <site> <x> <y> <orient> <num_x> <num_y> <step_x> <step_y>  #
##############################################################################
DefRow: ROW_118 core_2800 20.1600 350.5600 FS 1216 1 0.2800 0.0000
DefRow: ROW_117 core_2800 20.1600 347.7600 N 1216 1 0.2800 0.0000
DefRow: ROW_116 core_2800 20.1600 344.9600 FS 1216 1 0.2800 0.0000
DefRow: ROW_115 core_2800 20.1600 342.1600 N 1216 1 0.2800 0.0000
DefRow: ROW_114 core_2800 20.1600 339.3600 FS 1216 1 0.2800 0.0000
DefRow: ROW_113 core_2800 20.1600 336.5600 N 1216 1 0.2800 0.0000
DefRow: ROW_112 core_2800 20.1600 333.7600 FS 1216 1 0.2800 0.0000
DefRow: ROW_111 core_2800 20.1600 330.9600 N 1216 1 0.2800 0.0000
DefRow: ROW_110 core_2800 20.1600 328.1600 FS 1216 1 0.2800 0.0000
DefRow: ROW_109 core_2800 20.1600 325.3600 N 1216 1 0.2800 0.0000
DefRow: ROW_108 core_2800 20.1600 322.5600 FS 1216 1 0.2800 0.0000
DefRow: ROW_107 core_2800 20.1600 319.7600 N 1216 1 0.2800 0.0000
DefRow: ROW_106 core_2800 20.1600 316.9600 FS 1216 1 0.2800 0.0000
DefRow: ROW_105 core_2800 20.1600 314.1600 N 1216 1 0.2800 0.0000
DefRow: ROW_104 core_2800 20.1600 311.3600 FS 1216 1 0.2800 0.0000
DefRow: ROW_103 core_2800 20.1600 308.5600 N 1216 1 0.2800 0.0000
DefRow: ROW_102 core_2800 20.1600 305.7600 FS 1216 1 0.2800 0.0000
DefRow: ROW_101 core_2800 20.1600 302.9600 N 1216 1 0.2800 0.0000
DefRow: ROW_100 core_2800 20.1600 300.1600 FS 1216 1 0.2800 0.0000
DefRow: ROW_99 core_2800 20.1600 297.3600 N 1216 1 0.2800 0.0000
DefRow: ROW_98 core_2800 20.1600 294.5600 FS 1216 1 0.2800 0.0000
DefRow: ROW_97 core_2800 20.1600 291.7600 N 1216 1 0.2800 0.0000
DefRow: ROW_96 core_2800 20.1600 288.9600 FS 1216 1 0.2800 0.0000
DefRow: ROW_95 core_2800 20.1600 286.1600 N 1216 1 0.2800 0.0000
DefRow: ROW_94 core_2800 20.1600 283.3600 FS 1216 1 0.2800 0.0000
DefRow: ROW_93 core_2800 20.1600 280.5600 N 1216 1 0.2800 0.0000
DefRow: ROW_92 core_2800 20.1600 277.7600 FS 1216 1 0.2800 0.0000
DefRow: ROW_91 core_2800 20.1600 274.9600 N 1216 1 0.2800 0.0000
DefRow: ROW_90 core_2800 20.1600 272.1600 FS 1216 1 0.2800 0.0000
DefRow: ROW_89 core_2800 20.1600 269.3600 N 1216 1 0.2800 0.0000
DefRow: ROW_88 core_2800 20.1600 266.5600 FS 1216 1 0.2800 0.0000
DefRow: ROW_87 core_2800 20.1600 263.7600 N 1216 1 0.2800 0.0000
DefRow: ROW_86 core_2800 20.1600 260.9600 FS 1216 1 0.2800 0.0000
DefRow: ROW_85 core_2800 20.1600 258.1600 N 1216 1 0.2800 0.0000
DefRow: ROW_84 core_2800 20.1600 255.3600 FS 1216 1 0.2800 0.0000
DefRow: ROW_83 core_2800 20.1600 252.5600 N 1216 1 0.2800 0.0000
DefRow: ROW_82 core_2800 20.1600 249.7600 FS 1216 1 0.2800 0.0000
DefRow: ROW_81 core_2800 20.1600 246.9600 N 1216 1 0.2800 0.0000
DefRow: ROW_80 core_2800 20.1600 244.1600 FS 1216 1 0.2800 0.0000
DefRow: ROW_79 core_2800 20.1600 241.3600 N 1216 1 0.2800 0.0000
DefRow: ROW_78 core_2800 20.1600 238.5600 FS 1216 1 0.2800 0.0000
DefRow: ROW_77 core_2800 20.1600 235.7600 N 1216 1 0.2800 0.0000
DefRow: ROW_76 core_2800 20.1600 232.9600 FS 1216 1 0.2800 0.0000
DefRow: ROW_75 core_2800 20.1600 230.1600 N 1216 1 0.2800 0.0000
DefRow: ROW_74 core_2800 20.1600 227.3600 FS 1216 1 0.2800 0.0000
DefRow: ROW_73 core_2800 20.1600 224.5600 N 1216 1 0.2800 0.0000
DefRow: ROW_72 core_2800 20.1600 221.7600 FS 1216 1 0.2800 0.0000
DefRow: ROW_71 core_2800 20.1600 218.9600 N 1216 1 0.2800 0.0000
DefRow: ROW_70 core_2800 20.1600 216.1600 FS 1216 1 0.2800 0.0000
DefRow: ROW_69 core_2800 20.1600 213.3600 N 1216 1 0.2800 0.0000
DefRow: ROW_68 core_2800 20.1600 210.5600 FS 1216 1 0.2800 0.0000
DefRow: ROW_67 core_2800 20.1600 207.7600 N 1216 1 0.2800 0.0000
DefRow: ROW_66 core_2800 20.1600 204.9600 FS 1216 1 0.2800 0.0000
DefRow: ROW_65 core_2800 20.1600 202.1600 N 1216 1 0.2800 0.0000
DefRow: ROW_64 core_2800 20.1600 199.3600 FS 1216 1 0.2800 0.0000
DefRow: ROW_63 core_2800 20.1600 196.5600 N 1216 1 0.2800 0.0000
DefRow: ROW_62 core_2800 20.1600 193.7600 FS 1216 1 0.2800 0.0000
DefRow: ROW_61 core_2800 20.1600 190.9600 N 1216 1 0.2800 0.0000
DefRow: ROW_60 core_2800 20.1600 188.1600 FS 1216 1 0.2800 0.0000
DefRow: ROW_59 core_2800 20.1600 185.3600 N 1216 1 0.2800 0.0000
DefRow: ROW_58 core_2800 20.1600 182.5600 FS 1216 1 0.2800 0.0000
DefRow: ROW_57 core_2800 20.1600 179.7600 N 1216 1 0.2800 0.0000
DefRow: ROW_56 core_2800 20.1600 176.9600 FS 1216 1 0.2800 0.0000
DefRow: ROW_55 core_2800 20.1600 174.1600 N 1216 1 0.2800 0.0000
DefRow: ROW_54 core_2800 20.1600 171.3600 FS 1216 1 0.2800 0.0000
DefRow: ROW_53 core_2800 20.1600 168.5600 N 1216 1 0.2800 0.0000
DefRow: ROW_52 core_2800 20.1600 165.7600 FS 1216 1 0.2800 0.0000
DefRow: ROW_51 core_2800 20.1600 162.9600 N 1216 1 0.2800 0.0000
DefRow: ROW_50 core_2800 20.1600 160.1600 FS 1216 1 0.2800 0.0000
DefRow: ROW_49 core_2800 20.1600 157.3600 N 1216 1 0.2800 0.0000
DefRow: ROW_48 core_2800 20.1600 154.5600 FS 1216 1 0.2800 0.0000
DefRow: ROW_47 core_2800 20.1600 151.7600 N 1216 1 0.2800 0.0000
DefRow: ROW_46 core_2800 20.1600 148.9600 FS 1216 1 0.2800 0.0000
DefRow: ROW_45 core_2800 20.1600 146.1600 N 1216 1 0.2800 0.0000
DefRow: ROW_44 core_2800 20.1600 143.3600 FS 1216 1 0.2800 0.0000
DefRow: ROW_43 core_2800 20.1600 140.5600 N 1216 1 0.2800 0.0000
DefRow: ROW_42 core_2800 20.1600 137.7600 FS 1216 1 0.2800 0.0000
DefRow: ROW_41 core_2800 20.1600 134.9600 N 1216 1 0.2800 0.0000
DefRow: ROW_40 core_2800 20.1600 132.1600 FS 1216 1 0.2800 0.0000
DefRow: ROW_39 core_2800 20.1600 129.3600 N 1216 1 0.2800 0.0000
DefRow: ROW_38 core_2800 20.1600 126.5600 FS 1216 1 0.2800 0.0000
DefRow: ROW_37 core_2800 20.1600 123.7600 N 1216 1 0.2800 0.0000
DefRow: ROW_36 core_2800 20.1600 120.9600 FS 1216 1 0.2800 0.0000
DefRow: ROW_35 core_2800 20.1600 118.1600 N 1216 1 0.2800 0.0000
DefRow: ROW_34 core_2800 20.1600 115.3600 FS 1216 1 0.2800 0.0000
DefRow: ROW_33 core_2800 20.1600 112.5600 N 1216 1 0.2800 0.0000
DefRow: ROW_32 core_2800 20.1600 109.7600 FS 1216 1 0.2800 0.0000
DefRow: ROW_31 core_2800 20.1600 106.9600 N 1216 1 0.2800 0.0000
DefRow: ROW_30 core_2800 20.1600 104.1600 FS 1216 1 0.2800 0.0000
DefRow: ROW_29 core_2800 20.1600 101.3600 N 1216 1 0.2800 0.0000
DefRow: ROW_28 core_2800 20.1600 98.5600 FS 1216 1 0.2800 0.0000
DefRow: ROW_27 core_2800 20.1600 95.7600 N 1216 1 0.2800 0.0000
DefRow: ROW_26 core_2800 20.1600 92.9600 FS 1216 1 0.2800 0.0000
DefRow: ROW_25 core_2800 20.1600 90.1600 N 1216 1 0.2800 0.0000
DefRow: ROW_24 core_2800 20.1600 87.3600 FS 1216 1 0.2800 0.0000
DefRow: ROW_23 core_2800 20.1600 84.5600 N 1216 1 0.2800 0.0000
DefRow: ROW_22 core_2800 20.1600 81.7600 FS 1216 1 0.2800 0.0000
DefRow: ROW_21 core_2800 20.1600 78.9600 N 1216 1 0.2800 0.0000
DefRow: ROW_20 core_2800 20.1600 76.1600 FS 1216 1 0.2800 0.0000
DefRow: ROW_19 core_2800 20.1600 73.3600 N 1216 1 0.2800 0.0000
DefRow: ROW_18 core_2800 20.1600 70.5600 FS 1216 1 0.2800 0.0000
DefRow: ROW_17 core_2800 20.1600 67.7600 N 1216 1 0.2800 0.0000
DefRow: ROW_16 core_2800 20.1600 64.9600 FS 1216 1 0.2800 0.0000
DefRow: ROW_15 core_2800 20.1600 62.1600 N 1216 1 0.2800 0.0000
DefRow: ROW_14 core_2800 20.1600 59.3600 FS 1216 1 0.2800 0.0000
DefRow: ROW_13 core_2800 20.1600 56.5600 N 1216 1 0.2800 0.0000
DefRow: ROW_12 core_2800 20.1600 53.7600 FS 1216 1 0.2800 0.0000
DefRow: ROW_11 core_2800 20.1600 50.9600 N 1216 1 0.2800 0.0000
DefRow: ROW_10 core_2800 20.1600 48.1600 FS 1216 1 0.2800 0.0000
DefRow: ROW_9 core_2800 20.1600 45.3600 N 1216 1 0.2800 0.0000
DefRow: ROW_8 core_2800 20.1600 42.5600 FS 1216 1 0.2800 0.0000
DefRow: ROW_7 core_2800 20.1600 39.7600 N 1216 1 0.2800 0.0000
DefRow: ROW_6 core_2800 20.1600 36.9600 FS 1216 1 0.2800 0.0000
DefRow: ROW_5 core_2800 20.1600 34.1600 N 1216 1 0.2800 0.0000
DefRow: ROW_4 core_2800 20.1600 31.3600 FS 1216 1 0.2800 0.0000
DefRow: ROW_3 core_2800 20.1600 28.5600 N 1216 1 0.2800 0.0000
DefRow: ROW_2 core_2800 20.1600 25.7600 FS 1216 1 0.2800 0.0000
DefRow: ROW_1 core_2800 20.1600 22.9600 N 1216 1 0.2800 0.0000
DefRow: ROW_0 core_2800 20.1600 20.1600 FS 1216 1 0.2800 0.0000

#######################################################################################################
#  Track: dir start number space layer_num layer1 [firstColor] [isSameColor] [width] [rule] [isRectOnly]#
#######################################################################################################
Track: Y 0.5600 666 0.5600 1 8
Track: X 0.2800 680 0.5600 1 8
Track: X 0.1400 1360 0.2800 1 7
Track: Y 0.5600 666 0.5600 1 7
Track: Y 0.2800 1333 0.2800 1 6
Track: X 0.1400 1360 0.2800 1 6
Track: X 0.1400 1360 0.2800 1 5
Track: Y 0.2800 1333 0.2800 1 5
Track: Y 0.2800 1333 0.2800 1 4
Track: X 0.1400 1360 0.2800 1 4
Track: X 0.1400 1360 0.2800 1 3
Track: Y 0.2800 1333 0.2800 1 3
Track: Y 0.2800 1333 0.2800 1 2
Track: X 0.1400 1360 0.2800 1 2
Track: X 0.1400 1360 0.2800 1 1
Track: Y 0.2800 1333 0.2800 1 1

######################################################
#  GCellGrid: dir start number space                 #
######################################################
GCellGrid: Y 0.0000 2 0.2800
GCellGrid: Y 0.2800 134 2.8000
GCellGrid: Y 372.6800 2 0.8400
GCellGrid: X 0.0000 2 0.1400
GCellGrid: X 0.1400 136 2.8000
GCellGrid: X 378.1400 2 2.6600

###############################1p########################
#  <SelectiveBlockage>                                #
#     <cell name="cell_name" />                     #
#  </SelectiveBlockage                                #
#######################################################

######################################################
#  ScanGroup: groupName startPin stopPin             #
######################################################

######################################################
#  JtagCell:  leafCellName                           #
#  JtagInst:  <instName | HInstName>                 #
######################################################

#########################################################
#  PhysicalNet: <name> [-pwr|-gnd|-tiehi|-tielo]        #
#########################################################
PhysicalNet: VDD -pwr
PhysicalNet: GND -gnd

#####################################################################################
# <PGNets>                                                                          #
#    <PGNet name="net_name">                                                        #
#       <HNet name="hnet_name">                                                     #
#          <Port hinst="hinst_name" name="port_name" direction="in|out|inout" />    #
#       </HNet>                                                                     #
#    </PGNet>                                                                       #
# </PGNets>                                                                         #
#####################################################################################

#########################################################
#  PhysicalInstance: <name> <cell> <orient> <llx> <lly> #
#########################################################

######################################################
#  SpareCell: cellName                               #
#  SpareInst: instName                               #
######################################################

#####################################################################
#  Group: <group_name> <nrHinst> [-isPhyHier]                       #
#    <inst_name>                                                    #
#    ...                                                            #
#####################################################################

#####################################################################
#  Fence:  <name> <llx> <lly> <urx> <ury> <nrConstraintBox>         #
#    ConstraintBox: <llx> <lly> <urx> <ury>                         #
#    ...                                                            #
#  Region: <name> <llx> <lly> <urx> <ury> <nrConstraintBox>         #
#    ConstraintBox: <llx> <lly> <urx> <ury>                         #
#    ...                                                            #
#  Guide:  <name> <llx> <lly> <urx> <ury> <nrConstraintBox>         #
#    ConstraintBox: <llx> <lly> <urx> <ury>                         #
#    ...                                                            #
#  SoftGuide: <name>                                                #
#    ...                                                            #
#####################################################################

###########################################################################
#  <Constraints>                                                          #
#     <Constraint  type="fence|guide|region|softguide"                    #
#                  readonly=1  name="blk_name">                           #
#       <Box llx=1 lly=2 urx=3 ury=4 /> ...                               #
#     </Constraint>                                                       #
#  </Constraints>                                                         #
###########################################################################

###########################################################################
#  <macro_place_constraint>                                               #
#          ...                                                            #
#  </macro_place_constraint>                                              #
###########################################################################

######################################################################################
#  BlackBox: -cell <cell_name> { -size <x> <y> |  -area <um^2> | \                  #
#            -gatecount <count> <areapergate> <utilization> | \                     #
#            {-gateArea <gateAreaValue> [-macroArea <macroAreaValue>]} } \          #
#            [-minwidth <w> | -minheight <h> | -fixedwidh <w> | -fixedheight <h>] \ #
#            [-aspectratio <ratio>]                                                  #
#            [-boxList <nrConstraintBox>                                             #
#              ConstraintBox: <llx> <lly> <urx> <ury>                                #
#              ... ]                                                                 #
######################################################################################

#######################################################################################
#  <Blackboxes>                                                                       #
#     <Blackbox  cell=name  width=N height=N                                          #
#                { area=A | gatecount=N areaPerGate=A cellUtil=F |                    #
#                  gateArea=F {macroArea=F | macorList='str'} includeMacroArea={0|1}} #
#                [minWidth=N | minHeight=N | fixedWidh=N | fixedHeight=N]             #
#                [aspectRatio=R] >                                                    #
#         <Box llx=float lly=float urx=float ury=float /> ...                         #
#     </Blackbox>                                                                     #
#  </Blackboxes>                                                                      #
#######################################################################################

######################################################
#  Instance: <name> <orient> <llx> <lly>             #
######################################################

#################################################################
#  Block: <name> <orient> [<llx> <lly>]                         #
#         [<haloLeftMargin>  <haloBottomMargin>                 #
#          <haloRightMargin> <haloTopMargin> <haloFromInstBox>] #
#         [<IsInstDefCovered> <IsInstPreplaced>]                #
#                                                               #
#  Block with INT_MAX loc is for recording the halo block with  #
#  non-prePlaced status                                         #
#################################################################

###########################################################################
#  BlockRoutingHalo: <name> <space> <bottomLayer> <topLayer> <-lithoHalo> #
###########################################################################

######################################################
#  BlockLayerObstruct: <name> <layerX> ...           #
######################################################

######################################################
#  FeedthroughBuffer: <instName>                     #
######################################################

###########################################################################
#  <HierarchicalPartitions>                                               #
#     <GlobalPinConstraints>                                              #
#         <PinSpacing spacing=val />                                      #
#         <PinSpacing layer=layerId spacing=val />                        #
#         <PinWidth layer=layerId width=val />                            #
#         <PinDepth layer=layerId depth=val />                            #
#         <CornerToPinDistance distance=val />                            #
#     </GlobalPinConstraints>                                             #
#     <CellPtnCut name="name" cuts=Num >                                  #
#        <Box llx=11.0 lly=22.0 urx=33.0 ury=44.0 /> ...                  #
#     </CellPtnCut>                                                       #
#     <NetGroup name="group_name" nets=val spacing=val isOptOrder=val   #
#         isAltLayer=val isPffGroup=val isSpreadPin=val                   #
#         isExcludeAllLayer=val isExcludeSameLayer=val keepOutDistance=val#
#         isPureExclude=val isCompactArea=val isMixedSignal=val >         #
#         <Net name="net_name" /> ...                                   #
#     </NetGroup>                                                         #
#     <Partition name="ptn_name"  hinst="name"                            #
#         coreToLeft=fval coreToRight=fval coreToTop=fval                 #
#         coreToBottom=val pinSpacingNorth=val pinSpacingWest=val         #
#         pinSpacingSouth=val pinSpacingEast=val  blockedLayers=xval >    #
#         <TrackHalfPitch Horizontal=val Vertical=val />                  #
#         <SpacingHalo left=10.0 right=11.0 top=11.0 bottom=11.0 />       #
#         <Clone hinst="hinst_name" orient=R0|R90|... />                  #
#         <PinLayer side="N|W|S|E" Metal1=yes Metal2=yes ... />           #
#         <RowSize cellHeight=1.0 railWidth=1.0 />                        #
#         <DefaultTechSite name="core" />                                   #
#         <RoutingHalo sideSize=11.0 bottomLayer=M1 topLayer=M2  />       #
#         <SpacingHalo left=11.0 right=11.0 top=11.0 bottom=11.0 />       #
#         <PinToCornerDistance  totalCorners=nrCorners >                  #
#            <Corner number=<cornerNumber> distance=<distance> /> ...     #
#         </PinToCornerDistance >                                         #
#         <PinSpacingArea llx=val lly=val urx=val ury=val spacing=val />  #
#         <LayerWidthDepth layer=layerId width=w depth=d spacing=val />   #
#         <PinConstraint>                                                 #
#            <Pin name="pinName" >                                      #
#               <edge2 edgeMap=val />                                    #
#               <spacing space=val />                                    #
#               <layer layerMap=xval />                                  #
#               <pinWidth width=val />                                   #
#               <pinDepth depth=val />                                   #
#               <location x=val y=val />                                 #
#            </Pin>                                                       #
#         </PinConstraint>                                                #
#     </Partition>                                                        #
#     <CellPinGroup name="group_name" cell="cell_name" pins=nr        #
#         spacing=val isOptOrder=val isAltLayer=val isSpreadPin=val       #
#         isExcludeAllLayer=val isExcludeSameLayer=val keepOutDistance=val#
#         isPureExclude=val isCompactArea=val >                           #
#         <GroupFTerm name="term_name" /> ...                             #
#     </CellPinGroup>                                                     #
#     <PartitionPinBlockage layerMap=x llx=1 lly=2 urx=3 ury=4 name="n" />#
#     <PinGuide name="name" boxes=num layerPriority=val cell="name" >     #
#        <Box llx=11.0 lly=22.0 urx=33.0 ury=44.0 layer=id /> ...         #
#     </PinGuide>                                                         #
#  </HierarchicalPartitions>                                              #
###########################################################################
<HierarchicalPartitions>
    <GlobalPinConstraints>
        <PinSpacing spacing=2 />
        <CornerToPinDistance distance=5 />
    </GlobalPinConstraints>
    <Partition name="core" hinst="" coreToLeft=0.0000 coreToRight=0.0000 coreToTop=0.0000 coreToBottom=0.0000 pinSpacingNorth=-1 pinSpacingWest=-1 pinSpacingSouth=-1 pinSpacingEast=-1 blockedLayers=0xff orient=R0>
	<PinLayer side="N" Metal2=yes Metal4=yes Metal6=yes Metal8=yes />
	<PinLayer side="W" Metal3=yes Metal5=yes Metal7=yes />
	<PinLayer side="S" Metal2=yes Metal4=yes Metal6=yes Metal8=yes />
	<PinLayer side="E" Metal3=yes Metal5=yes Metal7=yes />
    <PinToCornerDistance totalCorners=4 >
      <Corner number=0 distance=-1 />
      <Corner number=1 distance=-1 />
      <Corner number=2 distance=-1 />
      <Corner number=3 distance=-1 />
    </PinToCornerDistance>
    </Partition>
</HierarchicalPartitions>

####################################################################################
#  <PlacementBlockages>                                                            #
#     <Blockage name="blk_name" type="hard|soft|partial">                      #
#       <Attr density=1.2 excludeFlops=yes inst="inst_name" pushdown=yes />      #
#       <Box llx=1 lly=2 urx=3 ury=4 /> ...                                        #
#     </Blockage>                                                                  #
#  </PlacementBlockages>                                                           #
####################################################################################

#################################################################
#  <SizeBlockages>                                             #
#     <Blockage name="blk_name">                              #
#       <Box llx=1 lly=2 urx=3 ury=4 /> ...                     #
#     </Blockage>                                               #
#  </SizeBlockages>                                            #
#################################################################

##########################################################################################################################
#  <RouteBlockages>                                                                                                      #
#     <Blockage name="blk_name" type="User|RouteGuide|PtnCut|WideWire">                                              #
#       <Attr spacing=1.2 drw=1.2 inst="name" pushdown=yes fills=yes exceptpgnet=yes pgnetonly=yes coreeolblkg=yes />  #
#       <Layer type="route|cut|masterslice" id=layerNo />                                                              #
#       <Box llx=1 lly=2 urx=3 ury=4 /> ...                                                                              #
#       <Poly points=nr x0=1 y0=1 x1=2 y2=2 ...  />                                                                      #
#     </Blockage>                                                                                                        #
#  </RouteBlockages>                                                                                                     #
##########################################################################################################################

######################################################
#  NetWeight: <net_name> <weight (in integer)>       #
######################################################

###########################################################################################
# NetbottomPreferredRoutingLayer:  <net_name> <bottomPreferredRoutingLayer (in integer)>  #
###########################################################################################

################################################################
# NetAvoidDetour:  <net_name>  < avoidDetour  { 1| 0}>   #
################################################################

#################################################################
#  SprFile: <file_name>                                         #
#################################################################
SprFile: core.fp.spr

##############################################################################
#  <IOPins>                                                                  #
#    <Pin name="pin_name" type="clock|power|ground|analog"                   #
#         status="covered|fixed|placed" is_special=1 >                       #
#      <Port>                                                                #
#        <Pref x=1 y=2 side="N|S|W|E|U|D" width=w depth=d orientation=val /> #
#        <Via name="via_name" x=1 y=2 BotMask=2 CutMask=1 TopMask=2 />...  #
#        <Layer id=id spacing=1.2 drw=1.2>                                   #
#          <Box llx=1 lly=2 urx=3 ury=4 /> ...                               #
#          <Poly points=nr x0=1 y0=1 x1=2 y2=2 ...           />              #
#        </Layer> ...                                                        #
#      </Port>  ...                                                          #
#      <NETEXPR>                                                             #
#        ground VSS                                                          #
#      </NETEXPR> ...                                                        #
#      <Antenna model=num type="name" value=float_num layer=num /> ...       #
#    </Pin> ...                                                              #
#  </IOPins>                                                                 #
##############################################################################

<IOPins>
  <Pin name="clk" >
  </Pin>
  <Pin name="rst_n" >
  </Pin>
  <Pin name="rom_rd_en1" >
  </Pin>
  <Pin name="rom_addr1[9]" >
  </Pin>
  <Pin name="rom_addr1[8]" >
  </Pin>
  <Pin name="rom_addr1[7]" >
  </Pin>
  <Pin name="rom_addr1[6]" >
  </Pin>
  <Pin name="rom_addr1[5]" >
  </Pin>
  <Pin name="rom_addr1[4]" >
  </Pin>
  <Pin name="rom_addr1[3]" >
  </Pin>
  <Pin name="rom_addr1[2]" >
  </Pin>
  <Pin name="rom_addr1[1]" >
  </Pin>
  <Pin name="rom_addr1[0]" >
  </Pin>
  <Pin name="rom_rd_data1[31]" >
  </Pin>
  <Pin name="rom_rd_data1[30]" >
  </Pin>
  <Pin name="rom_rd_data1[29]" >
  </Pin>
  <Pin name="rom_rd_data1[28]" >
  </Pin>
  <Pin name="rom_rd_data1[27]" >
  </Pin>
  <Pin name="rom_rd_data1[26]" >
  </Pin>
  <Pin name="rom_rd_data1[25]" >
  </Pin>
  <Pin name="rom_rd_data1[24]" >
  </Pin>
  <Pin name="rom_rd_data1[23]" >
  </Pin>
  <Pin name="rom_rd_data1[22]" >
  </Pin>
  <Pin name="rom_rd_data1[21]" >
  </Pin>
  <Pin name="rom_rd_data1[20]" >
  </Pin>
  <Pin name="rom_rd_data1[19]" >
  </Pin>
  <Pin name="rom_rd_data1[18]" >
  </Pin>
  <Pin name="rom_rd_data1[17]" >
  </Pin>
  <Pin name="rom_rd_data1[16]" >
  </Pin>
  <Pin name="rom_rd_data1[15]" >
  </Pin>
  <Pin name="rom_rd_data1[14]" >
  </Pin>
  <Pin name="rom_rd_data1[13]" >
  </Pin>
  <Pin name="rom_rd_data1[12]" >
  </Pin>
  <Pin name="rom_rd_data1[11]" >
  </Pin>
  <Pin name="rom_rd_data1[10]" >
  </Pin>
  <Pin name="rom_rd_data1[9]" >
  </Pin>
  <Pin name="rom_rd_data1[8]" >
  </Pin>
  <Pin name="rom_rd_data1[7]" >
  </Pin>
  <Pin name="rom_rd_data1[6]" >
  </Pin>
  <Pin name="rom_rd_data1[5]" >
  </Pin>
  <Pin name="rom_rd_data1[4]" >
  </Pin>
  <Pin name="rom_rd_data1[3]" >
  </Pin>
  <Pin name="rom_rd_data1[2]" >
  </Pin>
  <Pin name="rom_rd_data1[1]" >
  </Pin>
  <Pin name="rom_rd_data1[0]" >
  </Pin>
  <Pin name="rom_rd_en2" >
  </Pin>
  <Pin name="rom_addr2[9]" >
  </Pin>
  <Pin name="rom_addr2[8]" >
  </Pin>
  <Pin name="rom_addr2[7]" >
  </Pin>
  <Pin name="rom_addr2[6]" >
  </Pin>
  <Pin name="rom_addr2[5]" >
  </Pin>
  <Pin name="rom_addr2[4]" >
  </Pin>
  <Pin name="rom_addr2[3]" >
  </Pin>
  <Pin name="rom_addr2[2]" >
  </Pin>
  <Pin name="rom_addr2[1]" >
  </Pin>
  <Pin name="rom_addr2[0]" >
  </Pin>
  <Pin name="rom_rd_data2[31]" >
  </Pin>
  <Pin name="rom_rd_data2[30]" >
  </Pin>
  <Pin name="rom_rd_data2[29]" >
  </Pin>
  <Pin name="rom_rd_data2[28]" >
  </Pin>
  <Pin name="rom_rd_data2[27]" >
  </Pin>
  <Pin name="rom_rd_data2[26]" >
  </Pin>
  <Pin name="rom_rd_data2[25]" >
  </Pin>
  <Pin name="rom_rd_data2[24]" >
  </Pin>
  <Pin name="rom_rd_data2[23]" >
  </Pin>
  <Pin name="rom_rd_data2[22]" >
  </Pin>
  <Pin name="rom_rd_data2[21]" >
  </Pin>
  <Pin name="rom_rd_data2[20]" >
  </Pin>
  <Pin name="rom_rd_data2[19]" >
  </Pin>
  <Pin name="rom_rd_data2[18]" >
  </Pin>
  <Pin name="rom_rd_data2[17]" >
  </Pin>
  <Pin name="rom_rd_data2[16]" >
  </Pin>
  <Pin name="rom_rd_data2[15]" >
  </Pin>
  <Pin name="rom_rd_data2[14]" >
  </Pin>
  <Pin name="rom_rd_data2[13]" >
  </Pin>
  <Pin name="rom_rd_data2[12]" >
  </Pin>
  <Pin name="rom_rd_data2[11]" >
  </Pin>
  <Pin name="rom_rd_data2[10]" >
  </Pin>
  <Pin name="rom_rd_data2[9]" >
  </Pin>
  <Pin name="rom_rd_data2[8]" >
  </Pin>
  <Pin name="rom_rd_data2[7]" >
  </Pin>
  <Pin name="rom_rd_data2[6]" >
  </Pin>
  <Pin name="rom_rd_data2[5]" >
  </Pin>
  <Pin name="rom_rd_data2[4]" >
  </Pin>
  <Pin name="rom_rd_data2[3]" >
  </Pin>
  <Pin name="rom_rd_data2[2]" >
  </Pin>
  <Pin name="rom_rd_data2[1]" >
  </Pin>
  <Pin name="rom_rd_data2[0]" >
  </Pin>
  <Pin name="ram_rd_en" >
  </Pin>
  <Pin name="ram_wr_en" >
  </Pin>
  <Pin name="ram_addr[9]" >
  </Pin>
  <Pin name="ram_addr[8]" >
  </Pin>
  <Pin name="ram_addr[7]" >
  </Pin>
  <Pin name="ram_addr[6]" >
  </Pin>
  <Pin name="ram_addr[5]" >
  </Pin>
  <Pin name="ram_addr[4]" >
  </Pin>
  <Pin name="ram_addr[3]" >
  </Pin>
  <Pin name="ram_addr[2]" >
  </Pin>
  <Pin name="ram_addr[1]" >
  </Pin>
  <Pin name="ram_addr[0]" >
  </Pin>
  <Pin name="ram_rd_data[31]" >
  </Pin>
  <Pin name="ram_rd_data[30]" >
  </Pin>
  <Pin name="ram_rd_data[29]" >
  </Pin>
  <Pin name="ram_rd_data[28]" >
  </Pin>
  <Pin name="ram_rd_data[27]" >
  </Pin>
  <Pin name="ram_rd_data[26]" >
  </Pin>
  <Pin name="ram_rd_data[25]" >
  </Pin>
  <Pin name="ram_rd_data[24]" >
  </Pin>
  <Pin name="ram_rd_data[23]" >
  </Pin>
  <Pin name="ram_rd_data[22]" >
  </Pin>
  <Pin name="ram_rd_data[21]" >
  </Pin>
  <Pin name="ram_rd_data[20]" >
  </Pin>
  <Pin name="ram_rd_data[19]" >
  </Pin>
  <Pin name="ram_rd_data[18]" >
  </Pin>
  <Pin name="ram_rd_data[17]" >
  </Pin>
  <Pin name="ram_rd_data[16]" >
  </Pin>
  <Pin name="ram_rd_data[15]" >
  </Pin>
  <Pin name="ram_rd_data[14]" >
  </Pin>
  <Pin name="ram_rd_data[13]" >
  </Pin>
  <Pin name="ram_rd_data[12]" >
  </Pin>
  <Pin name="ram_rd_data[11]" >
  </Pin>
  <Pin name="ram_rd_data[10]" >
  </Pin>
  <Pin name="ram_rd_data[9]" >
  </Pin>
  <Pin name="ram_rd_data[8]" >
  </Pin>
  <Pin name="ram_rd_data[7]" >
  </Pin>
  <Pin name="ram_rd_data[6]" >
  </Pin>
  <Pin name="ram_rd_data[5]" >
  </Pin>
  <Pin name="ram_rd_data[4]" >
  </Pin>
  <Pin name="ram_rd_data[3]" >
  </Pin>
  <Pin name="ram_rd_data[2]" >
  </Pin>
  <Pin name="ram_rd_data[1]" >
  </Pin>
  <Pin name="ram_rd_data[0]" >
  </Pin>
  <Pin name="axi_rd_en" >
  </Pin>
  <Pin name="axi_wr_en" >
  </Pin>
  <Pin name="axi_addr[28]" >
  </Pin>
  <Pin name="axi_addr[27]" >
  </Pin>
  <Pin name="axi_addr[26]" >
  </Pin>
  <Pin name="axi_addr[25]" >
  </Pin>
  <Pin name="axi_addr[24]" >
  </Pin>
  <Pin name="axi_addr[23]" >
  </Pin>
  <Pin name="axi_addr[22]" >
  </Pin>
  <Pin name="axi_addr[21]" >
  </Pin>
  <Pin name="axi_addr[20]" >
  </Pin>
  <Pin name="axi_addr[19]" >
  </Pin>
  <Pin name="axi_addr[18]" >
  </Pin>
  <Pin name="axi_addr[17]" >
  </Pin>
  <Pin name="axi_addr[16]" >
  </Pin>
  <Pin name="axi_addr[15]" >
  </Pin>
  <Pin name="axi_addr[14]" >
  </Pin>
  <Pin name="axi_addr[13]" >
  </Pin>
  <Pin name="axi_addr[12]" >
  </Pin>
  <Pin name="axi_addr[11]" >
  </Pin>
  <Pin name="axi_addr[10]" >
  </Pin>
  <Pin name="axi_addr[9]" >
  </Pin>
  <Pin name="axi_addr[8]" >
  </Pin>
  <Pin name="axi_addr[7]" >
  </Pin>
  <Pin name="axi_addr[6]" >
  </Pin>
  <Pin name="axi_addr[5]" >
  </Pin>
  <Pin name="axi_addr[4]" >
  </Pin>
  <Pin name="axi_addr[3]" >
  </Pin>
  <Pin name="axi_addr[2]" >
  </Pin>
  <Pin name="axi_addr[1]" >
  </Pin>
  <Pin name="axi_addr[0]" >
  </Pin>
  <Pin name="axi_rd_data[31]" >
  </Pin>
  <Pin name="axi_rd_data[30]" >
  </Pin>
  <Pin name="axi_rd_data[29]" >
  </Pin>
  <Pin name="axi_rd_data[28]" >
  </Pin>
  <Pin name="axi_rd_data[27]" >
  </Pin>
  <Pin name="axi_rd_data[26]" >
  </Pin>
  <Pin name="axi_rd_data[25]" >
  </Pin>
  <Pin name="axi_rd_data[24]" >
  </Pin>
  <Pin name="axi_rd_data[23]" >
  </Pin>
  <Pin name="axi_rd_data[22]" >
  </Pin>
  <Pin name="axi_rd_data[21]" >
  </Pin>
  <Pin name="axi_rd_data[20]" >
  </Pin>
  <Pin name="axi_rd_data[19]" >
  </Pin>
  <Pin name="axi_rd_data[18]" >
  </Pin>
  <Pin name="axi_rd_data[17]" >
  </Pin>
  <Pin name="axi_rd_data[16]" >
  </Pin>
  <Pin name="axi_rd_data[15]" >
  </Pin>
  <Pin name="axi_rd_data[14]" >
  </Pin>
  <Pin name="axi_rd_data[13]" >
  </Pin>
  <Pin name="axi_rd_data[12]" >
  </Pin>
  <Pin name="axi_rd_data[11]" >
  </Pin>
  <Pin name="axi_rd_data[10]" >
  </Pin>
  <Pin name="axi_rd_data[9]" >
  </Pin>
  <Pin name="axi_rd_data[8]" >
  </Pin>
  <Pin name="axi_rd_data[7]" >
  </Pin>
  <Pin name="axi_rd_data[6]" >
  </Pin>
  <Pin name="axi_rd_data[5]" >
  </Pin>
  <Pin name="axi_rd_data[4]" >
  </Pin>
  <Pin name="axi_rd_data[3]" >
  </Pin>
  <Pin name="axi_rd_data[2]" >
  </Pin>
  <Pin name="axi_rd_data[1]" >
  </Pin>
  <Pin name="axi_rd_data[0]" >
  </Pin>
  <Pin name="axi_access_fault" >
  </Pin>
  <Pin name="axi_busy" >
  </Pin>
  <Pin name="wr_data[31]" >
  </Pin>
  <Pin name="wr_data[30]" >
  </Pin>
  <Pin name="wr_data[29]" >
  </Pin>
  <Pin name="wr_data[28]" >
  </Pin>
  <Pin name="wr_data[27]" >
  </Pin>
  <Pin name="wr_data[26]" >
  </Pin>
  <Pin name="wr_data[25]" >
  </Pin>
  <Pin name="wr_data[24]" >
  </Pin>
  <Pin name="wr_data[23]" >
  </Pin>
  <Pin name="wr_data[22]" >
  </Pin>
  <Pin name="wr_data[21]" >
  </Pin>
  <Pin name="wr_data[20]" >
  </Pin>
  <Pin name="wr_data[19]" >
  </Pin>
  <Pin name="wr_data[18]" >
  </Pin>
  <Pin name="wr_data[17]" >
  </Pin>
  <Pin name="wr_data[16]" >
  </Pin>
  <Pin name="wr_data[15]" >
  </Pin>
  <Pin name="wr_data[14]" >
  </Pin>
  <Pin name="wr_data[13]" >
  </Pin>
  <Pin name="wr_data[12]" >
  </Pin>
  <Pin name="wr_data[11]" >
  </Pin>
  <Pin name="wr_data[10]" >
  </Pin>
  <Pin name="wr_data[9]" >
  </Pin>
  <Pin name="wr_data[8]" >
  </Pin>
  <Pin name="wr_data[7]" >
  </Pin>
  <Pin name="wr_data[6]" >
  </Pin>
  <Pin name="wr_data[5]" >
  </Pin>
  <Pin name="wr_data[4]" >
  </Pin>
  <Pin name="wr_data[3]" >
  </Pin>
  <Pin name="wr_data[2]" >
  </Pin>
  <Pin name="wr_data[1]" >
  </Pin>
  <Pin name="wr_data[0]" >
  </Pin>
  <Pin name="wr_strobe[3]" >
  </Pin>
  <Pin name="wr_strobe[2]" >
  </Pin>
  <Pin name="wr_strobe[1]" >
  </Pin>
  <Pin name="wr_strobe[0]" >
  </Pin>
  <Pin name="gpioa_int_0" >
  </Pin>
  <Pin name="gpioa_int_1" >
  </Pin>
  <Pin name="gpiob_int_0" >
  </Pin>
  <Pin name="gpiob_int_1" >
  </Pin>
  <Pin name="gpioc_int_0" >
  </Pin>
  <Pin name="gpioc_int_1" >
  </Pin>
  <Pin name="uart0_rx_int" >
  </Pin>
  <Pin name="uart0_tx_int" >
  </Pin>
  <Pin name="timer0_int" >
  </Pin>
  <Pin name="timer1_int" >
  </Pin>
</IOPins>

#####################################################################
#  <Property>                                                       #
#     <obj_type name="inst_name" >                                  #
#       <prop name="name" type=type_name value=val />               #
#       <Attr name="name" type=type_name value=val />               #
#     </obj_type>                                                   #
#  </Property>                                                      #
#  where:                                                           #
#       type is data type: Box, String, Int, PTR, Loc, double, Bits #
#       obj_type are: inst, Design, instTerm, Bump, cell, net       #
#####################################################################
<Properties>
  <Design name="core">
	<prop name="TDRCAppName" type=String value="OPT_LA:1 GPS_LA:2 " />
	<prop name="flow_implementation_stage" type=String value="place_opt" def=yes />
	<prop name="CUT_ROWS" type=Int value=0 />
  </Design>
</Properties>

################################################################################
#  NetProperties: <net_name> [-special] [-def_prop {int|dbl|str} <value>]...   #
################################################################################

##################################################################################
#    Feedthru info:                                                              #
# <Feedthrus>                                                                    #
#   <Feedthru>                                                                   #
#       <tsv llx=n lly=n urx=n ury=n />                                          #
#       <stackvia layer=z llx=n lly=n urx=n ury=n />                             #
#       <bump front=name back=name  />                                           #
#   </Feedthru>                                                                  #
#   <Feedthru>                                                                   #
#   <...>                                                                        #
#   </Feedthru>                                                                  #
# </Feedthrus>                                                                   #
################################################################################
